name: lovely_coffee
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.3
  hive: ^2.2.2
  dartz: ^0.10.1
  lottie: ^1.3.0
  equatable: ^2.0.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.0.1
  firebase_core: ^1.18.0
  google_sign_in: ^5.3.3
  firebase_auth: ^3.3.19
  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.18
  connectivity_plus: ^2.3.4
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  flutter_lints: ^2.0.0
  fake_cloud_firestore: ^1.2.2


flutter:
  uses-material-design: true

  assets:
    - assets/animations/